// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9MwePlmcocb8vK661aP3dszU6wMlO6b8',
    appId: '1:314903055891:web:00e189750b9d8f9f62f9e6',
    messagingSenderId: '314903055891',
    projectId: 'quizapp-638ce',
    authDomain: 'quizapp-638ce.firebaseapp.com',
    storageBucket: 'quizapp-638ce.appspot.com',
    measurementId: 'G-THD7T53TET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKjRBtRzfZHXa_083Zn27R2SEmGz7MDDI',
    appId: '1:314903055891:android:592f5d111ae1b67a62f9e6',
    messagingSenderId: '314903055891',
    projectId: 'quizapp-638ce',
    storageBucket: 'quizapp-638ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUO9mhVkiDTXl8KxaazV5ugvYJanz1SA',
    appId: '1:314903055891:ios:ac61ed129e9a164962f9e6',
    messagingSenderId: '314903055891',
    projectId: 'quizapp-638ce',
    storageBucket: 'quizapp-638ce.appspot.com',
    iosClientId:
        '314903055891-atdvd6pttsled1r0irnrlvlph7anmhu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.engquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUO9mhVkiDTXl8KxaazV5ugvYJanz1SA',
    appId: '1:314903055891:ios:ac61ed129e9a164962f9e6',
    messagingSenderId: '314903055891',
    projectId: 'quizapp-638ce',
    storageBucket: 'quizapp-638ce.appspot.com',
    iosClientId:
        '314903055891-atdvd6pttsled1r0irnrlvlph7anmhu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.engquiz',
  );
}
